// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Texture.proto

package com.eaglesakura.resource.texture;

public final class Texture {
  private Texture() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code jc_res_texture.PixelFormat}
   *
   * <pre>
   * テクスチャフォーマット
   * </pre>
   */
  public enum PixelFormat
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RGBA8888 = 0;</code>
     *
     * <pre>
     * </pre>
     */
    RGBA8888(0, 0),
    /**
     * <code>RGB888 = 1;</code>
     *
     * <pre>
     * </pre>
     */
    RGB888(1, 1),
    /**
     * <code>RGB565 = 2;</code>
     *
     * <pre>
     * </pre>
     */
    RGB565(2, 2),
    /**
     * <code>RGBA4444 = 3;</code>
     *
     * <pre>
     * </pre>
     */
    RGBA4444(3, 3),
    /**
     * <code>RGB5551 = 4;</code>
     *
     * <pre>
     * </pre>
     */
    RGB5551(4, 4),
    ;

    /**
     * <code>RGBA8888 = 0;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int RGBA8888_VALUE = 0;
    /**
     * <code>RGB888 = 1;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int RGB888_VALUE = 1;
    /**
     * <code>RGB565 = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int RGB565_VALUE = 2;
    /**
     * <code>RGBA4444 = 3;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int RGBA4444_VALUE = 3;
    /**
     * <code>RGB5551 = 4;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int RGB5551_VALUE = 4;


    public final int getNumber() { return value; }

    public static PixelFormat valueOf(int value) {
      switch (value) {
        case 0: return RGBA8888;
        case 1: return RGB888;
        case 2: return RGB565;
        case 3: return RGBA4444;
        case 4: return RGB5551;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PixelFormat>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PixelFormat>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PixelFormat>() {
            public PixelFormat findValueByNumber(int number) {
              return PixelFormat.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.eaglesakura.resource.texture.Texture.getDescriptor().getEnumTypes().get(0);
    }

    private static final PixelFormat[] VALUES = values();

    public static PixelFormat valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PixelFormat(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:jc_res_texture.PixelFormat)
  }

  /**
   * Protobuf enum {@code jc_res_texture.TextureFormat}
   *
   * <pre>
   * テクスチャの画像フォーマットを定義する
   * </pre>
   */
  public enum TextureFormat
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PNG = 0;</code>
     */
    PNG(0, 0),
    /**
     * <code>JPEG = 1;</code>
     */
    JPEG(1, 1),
    /**
     * <code>KTX = 2;</code>
     */
    KTX(2, 2),
    ;

    /**
     * <code>PNG = 0;</code>
     */
    public static final int PNG_VALUE = 0;
    /**
     * <code>JPEG = 1;</code>
     */
    public static final int JPEG_VALUE = 1;
    /**
     * <code>KTX = 2;</code>
     */
    public static final int KTX_VALUE = 2;


    public final int getNumber() { return value; }

    public static TextureFormat valueOf(int value) {
      switch (value) {
        case 0: return PNG;
        case 1: return JPEG;
        case 2: return KTX;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TextureFormat>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TextureFormat>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TextureFormat>() {
            public TextureFormat findValueByNumber(int number) {
              return TextureFormat.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.eaglesakura.resource.texture.Texture.getDescriptor().getEnumTypes().get(1);
    }

    private static final TextureFormat[] VALUES = values();

    public static TextureFormat valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TextureFormat(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:jc_res_texture.TextureFormat)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rTexture.proto\022\016jc_res_texture*N\n\013Pixel" +
      "Format\022\014\n\010RGBA8888\020\000\022\n\n\006RGB888\020\001\022\n\n\006RGB5" +
      "65\020\002\022\014\n\010RGBA4444\020\003\022\013\n\007RGB5551\020\004*+\n\rTextu" +
      "reFormat\022\007\n\003PNG\020\000\022\010\n\004JPEG\020\001\022\007\n\003KTX\020\002B\"\n " +
      "com.eaglesakura.resource.texture"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
