// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Primitive.proto

package com.eaglesakura.resource.primitive;

public final class Primitive {
  private Primitive() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RectangleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 x = 1000;
    /**
     * <code>required int32 x = 1000;</code>
     */
    boolean hasX();
    /**
     * <code>required int32 x = 1000;</code>
     */
    int getX();

    // required int32 y = 2000;
    /**
     * <code>required int32 y = 2000;</code>
     */
    boolean hasY();
    /**
     * <code>required int32 y = 2000;</code>
     */
    int getY();

    // required int32 w = 3000;
    /**
     * <code>required int32 w = 3000;</code>
     */
    boolean hasW();
    /**
     * <code>required int32 w = 3000;</code>
     */
    int getW();

    // required int32 h = 4000;
    /**
     * <code>required int32 h = 4000;</code>
     */
    boolean hasH();
    /**
     * <code>required int32 h = 4000;</code>
     */
    int getH();
  }
  /**
   * Protobuf type {@code jc_res.Rectangle}
   *
   * <pre>
   * 四角形
   * </pre>
   */
  public static final class Rectangle extends
      com.google.protobuf.GeneratedMessage
      implements RectangleOrBuilder {
    // Use Rectangle.newBuilder() to construct.
    private Rectangle(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Rectangle(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Rectangle defaultInstance;
    public static Rectangle getDefaultInstance() {
      return defaultInstance;
    }

    public Rectangle getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Rectangle(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8000: {
              bitField0_ |= 0x00000001;
              x_ = input.readInt32();
              break;
            }
            case 16000: {
              bitField0_ |= 0x00000002;
              y_ = input.readInt32();
              break;
            }
            case 24000: {
              bitField0_ |= 0x00000004;
              w_ = input.readInt32();
              break;
            }
            case 32000: {
              bitField0_ |= 0x00000008;
              h_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eaglesakura.resource.primitive.Primitive.internal_static_jc_res_Rectangle_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eaglesakura.resource.primitive.Primitive.internal_static_jc_res_Rectangle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eaglesakura.resource.primitive.Primitive.Rectangle.class, com.eaglesakura.resource.primitive.Primitive.Rectangle.Builder.class);
    }

    public static com.google.protobuf.Parser<Rectangle> PARSER =
        new com.google.protobuf.AbstractParser<Rectangle>() {
      public Rectangle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Rectangle(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Rectangle> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 x = 1000;
    public static final int X_FIELD_NUMBER = 1000;
    private int x_;
    /**
     * <code>required int32 x = 1000;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 x = 1000;</code>
     */
    public int getX() {
      return x_;
    }

    // required int32 y = 2000;
    public static final int Y_FIELD_NUMBER = 2000;
    private int y_;
    /**
     * <code>required int32 y = 2000;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 y = 2000;</code>
     */
    public int getY() {
      return y_;
    }

    // required int32 w = 3000;
    public static final int W_FIELD_NUMBER = 3000;
    private int w_;
    /**
     * <code>required int32 w = 3000;</code>
     */
    public boolean hasW() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 w = 3000;</code>
     */
    public int getW() {
      return w_;
    }

    // required int32 h = 4000;
    public static final int H_FIELD_NUMBER = 4000;
    private int h_;
    /**
     * <code>required int32 h = 4000;</code>
     */
    public boolean hasH() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 h = 4000;</code>
     */
    public int getH() {
      return h_;
    }

    private void initFields() {
      x_ = 0;
      y_ = 0;
      w_ = 0;
      h_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasW()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasH()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1000, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2000, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3000, w_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4000, h_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1000, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2000, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3000, w_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4000, h_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.eaglesakura.resource.primitive.Primitive.Rectangle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Rectangle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Rectangle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Rectangle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Rectangle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Rectangle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Rectangle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Rectangle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Rectangle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Rectangle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.eaglesakura.resource.primitive.Primitive.Rectangle prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jc_res.Rectangle}
     *
     * <pre>
     * 四角形
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.eaglesakura.resource.primitive.Primitive.RectangleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eaglesakura.resource.primitive.Primitive.internal_static_jc_res_Rectangle_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eaglesakura.resource.primitive.Primitive.internal_static_jc_res_Rectangle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eaglesakura.resource.primitive.Primitive.Rectangle.class, com.eaglesakura.resource.primitive.Primitive.Rectangle.Builder.class);
      }

      // Construct using com.eaglesakura.resource.primitive.Primitive.Rectangle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        w_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        h_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eaglesakura.resource.primitive.Primitive.internal_static_jc_res_Rectangle_descriptor;
      }

      public com.eaglesakura.resource.primitive.Primitive.Rectangle getDefaultInstanceForType() {
        return com.eaglesakura.resource.primitive.Primitive.Rectangle.getDefaultInstance();
      }

      public com.eaglesakura.resource.primitive.Primitive.Rectangle build() {
        com.eaglesakura.resource.primitive.Primitive.Rectangle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.eaglesakura.resource.primitive.Primitive.Rectangle buildPartial() {
        com.eaglesakura.resource.primitive.Primitive.Rectangle result = new com.eaglesakura.resource.primitive.Primitive.Rectangle(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.w_ = w_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.h_ = h_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eaglesakura.resource.primitive.Primitive.Rectangle) {
          return mergeFrom((com.eaglesakura.resource.primitive.Primitive.Rectangle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eaglesakura.resource.primitive.Primitive.Rectangle other) {
        if (other == com.eaglesakura.resource.primitive.Primitive.Rectangle.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasW()) {
          setW(other.getW());
        }
        if (other.hasH()) {
          setH(other.getH());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!hasW()) {
          
          return false;
        }
        if (!hasH()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eaglesakura.resource.primitive.Primitive.Rectangle parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eaglesakura.resource.primitive.Primitive.Rectangle) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 x = 1000;
      private int x_ ;
      /**
       * <code>required int32 x = 1000;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 x = 1000;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>required int32 x = 1000;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 x = 1000;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }

      // required int32 y = 2000;
      private int y_ ;
      /**
       * <code>required int32 y = 2000;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 y = 2000;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>required int32 y = 2000;</code>
       */
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 y = 2000;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }

      // required int32 w = 3000;
      private int w_ ;
      /**
       * <code>required int32 w = 3000;</code>
       */
      public boolean hasW() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 w = 3000;</code>
       */
      public int getW() {
        return w_;
      }
      /**
       * <code>required int32 w = 3000;</code>
       */
      public Builder setW(int value) {
        bitField0_ |= 0x00000004;
        w_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 w = 3000;</code>
       */
      public Builder clearW() {
        bitField0_ = (bitField0_ & ~0x00000004);
        w_ = 0;
        onChanged();
        return this;
      }

      // required int32 h = 4000;
      private int h_ ;
      /**
       * <code>required int32 h = 4000;</code>
       */
      public boolean hasH() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 h = 4000;</code>
       */
      public int getH() {
        return h_;
      }
      /**
       * <code>required int32 h = 4000;</code>
       */
      public Builder setH(int value) {
        bitField0_ |= 0x00000008;
        h_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 h = 4000;</code>
       */
      public Builder clearH() {
        bitField0_ = (bitField0_ & ~0x00000008);
        h_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jc_res.Rectangle)
    }

    static {
      defaultInstance = new Rectangle(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jc_res.Rectangle)
  }

  public interface SizeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 w = 1000;
    /**
     * <code>required int32 w = 1000;</code>
     */
    boolean hasW();
    /**
     * <code>required int32 w = 1000;</code>
     */
    int getW();

    // required int32 h = 2000;
    /**
     * <code>required int32 h = 2000;</code>
     */
    boolean hasH();
    /**
     * <code>required int32 h = 2000;</code>
     */
    int getH();
  }
  /**
   * Protobuf type {@code jc_res.Size}
   *
   * <pre>
   * アトラス化された画像
   * </pre>
   */
  public static final class Size extends
      com.google.protobuf.GeneratedMessage
      implements SizeOrBuilder {
    // Use Size.newBuilder() to construct.
    private Size(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Size(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Size defaultInstance;
    public static Size getDefaultInstance() {
      return defaultInstance;
    }

    public Size getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Size(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8000: {
              bitField0_ |= 0x00000001;
              w_ = input.readInt32();
              break;
            }
            case 16000: {
              bitField0_ |= 0x00000002;
              h_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eaglesakura.resource.primitive.Primitive.internal_static_jc_res_Size_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eaglesakura.resource.primitive.Primitive.internal_static_jc_res_Size_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eaglesakura.resource.primitive.Primitive.Size.class, com.eaglesakura.resource.primitive.Primitive.Size.Builder.class);
    }

    public static com.google.protobuf.Parser<Size> PARSER =
        new com.google.protobuf.AbstractParser<Size>() {
      public Size parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Size(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Size> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 w = 1000;
    public static final int W_FIELD_NUMBER = 1000;
    private int w_;
    /**
     * <code>required int32 w = 1000;</code>
     */
    public boolean hasW() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 w = 1000;</code>
     */
    public int getW() {
      return w_;
    }

    // required int32 h = 2000;
    public static final int H_FIELD_NUMBER = 2000;
    private int h_;
    /**
     * <code>required int32 h = 2000;</code>
     */
    public boolean hasH() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 h = 2000;</code>
     */
    public int getH() {
      return h_;
    }

    private void initFields() {
      w_ = 0;
      h_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasW()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasH()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1000, w_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2000, h_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1000, w_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2000, h_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.eaglesakura.resource.primitive.Primitive.Size parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Size parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Size parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Size parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Size parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Size parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Size parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Size parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Size parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.eaglesakura.resource.primitive.Primitive.Size parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.eaglesakura.resource.primitive.Primitive.Size prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jc_res.Size}
     *
     * <pre>
     * アトラス化された画像
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.eaglesakura.resource.primitive.Primitive.SizeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eaglesakura.resource.primitive.Primitive.internal_static_jc_res_Size_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eaglesakura.resource.primitive.Primitive.internal_static_jc_res_Size_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eaglesakura.resource.primitive.Primitive.Size.class, com.eaglesakura.resource.primitive.Primitive.Size.Builder.class);
      }

      // Construct using com.eaglesakura.resource.primitive.Primitive.Size.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        w_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        h_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eaglesakura.resource.primitive.Primitive.internal_static_jc_res_Size_descriptor;
      }

      public com.eaglesakura.resource.primitive.Primitive.Size getDefaultInstanceForType() {
        return com.eaglesakura.resource.primitive.Primitive.Size.getDefaultInstance();
      }

      public com.eaglesakura.resource.primitive.Primitive.Size build() {
        com.eaglesakura.resource.primitive.Primitive.Size result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.eaglesakura.resource.primitive.Primitive.Size buildPartial() {
        com.eaglesakura.resource.primitive.Primitive.Size result = new com.eaglesakura.resource.primitive.Primitive.Size(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.w_ = w_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.h_ = h_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eaglesakura.resource.primitive.Primitive.Size) {
          return mergeFrom((com.eaglesakura.resource.primitive.Primitive.Size)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eaglesakura.resource.primitive.Primitive.Size other) {
        if (other == com.eaglesakura.resource.primitive.Primitive.Size.getDefaultInstance()) return this;
        if (other.hasW()) {
          setW(other.getW());
        }
        if (other.hasH()) {
          setH(other.getH());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasW()) {
          
          return false;
        }
        if (!hasH()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eaglesakura.resource.primitive.Primitive.Size parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eaglesakura.resource.primitive.Primitive.Size) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 w = 1000;
      private int w_ ;
      /**
       * <code>required int32 w = 1000;</code>
       */
      public boolean hasW() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 w = 1000;</code>
       */
      public int getW() {
        return w_;
      }
      /**
       * <code>required int32 w = 1000;</code>
       */
      public Builder setW(int value) {
        bitField0_ |= 0x00000001;
        w_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 w = 1000;</code>
       */
      public Builder clearW() {
        bitField0_ = (bitField0_ & ~0x00000001);
        w_ = 0;
        onChanged();
        return this;
      }

      // required int32 h = 2000;
      private int h_ ;
      /**
       * <code>required int32 h = 2000;</code>
       */
      public boolean hasH() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 h = 2000;</code>
       */
      public int getH() {
        return h_;
      }
      /**
       * <code>required int32 h = 2000;</code>
       */
      public Builder setH(int value) {
        bitField0_ |= 0x00000002;
        h_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 h = 2000;</code>
       */
      public Builder clearH() {
        bitField0_ = (bitField0_ & ~0x00000002);
        h_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:jc_res.Size)
    }

    static {
      defaultInstance = new Size(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:jc_res.Size)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_jc_res_Rectangle_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jc_res_Rectangle_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_jc_res_Size_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jc_res_Size_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Primitive.proto\022\006jc_res\";\n\tRectangle\022\n" +
      "\n\001x\030\350\007 \002(\005\022\n\n\001y\030\320\017 \002(\005\022\n\n\001w\030\270\027 \002(\005\022\n\n\001h\030" +
      "\240\037 \002(\005\"\036\n\004Size\022\n\n\001w\030\350\007 \002(\005\022\n\n\001h\030\320\017 \002(\005B$" +
      "\n\"com.eaglesakura.resource.primitive"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_jc_res_Rectangle_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_jc_res_Rectangle_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jc_res_Rectangle_descriptor,
              new java.lang.String[] { "X", "Y", "W", "H", });
          internal_static_jc_res_Size_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_jc_res_Size_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_jc_res_Size_descriptor,
              new java.lang.String[] { "W", "H", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
