#! /bin/sh

PREBUILT=${ANDROID_NDK_HOME}/toolchains//arm-linux-androideabi-4.8
PLATFORM=${ANDROID_NDK_HOME}/platforms/android-14/arch-arm

export CC=${PREBUILT}/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc
export CFLAGS=-'fPIC -DANDROID -nostdlib'
export LDFLAGS="-Wl,-rpath-link=${PLATFORM}/usr/lib/ -L${PLATFORM}/usr/lib/"

export CPPFLAGS=-I${PLATFORM}/usr/include

export LIBS=-lc 
./configure --host=arm-eabi
