// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Primitive.proto

#ifndef PROTOBUF_Primitive_2eproto__INCLUDED
#define PROTOBUF_Primitive_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace jc_res {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Primitive_2eproto();
void protobuf_AssignDesc_Primitive_2eproto();
void protobuf_ShutdownFile_Primitive_2eproto();

class Rectangle;
class Size;

// ===================================================================

class Rectangle : public ::google::protobuf::Message {
 public:
  Rectangle();
  virtual ~Rectangle();

  Rectangle(const Rectangle& from);

  inline Rectangle& operator=(const Rectangle& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Rectangle& default_instance();

  void Swap(Rectangle* other);

  // implements Message ----------------------------------------------

  Rectangle* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Rectangle& from);
  void MergeFrom(const Rectangle& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 x = 1000;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1000;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);

  // required int32 y = 2000;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2000;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);

  // required int32 w = 3000;
  inline bool has_w() const;
  inline void clear_w();
  static const int kWFieldNumber = 3000;
  inline ::google::protobuf::int32 w() const;
  inline void set_w(::google::protobuf::int32 value);

  // required int32 h = 4000;
  inline bool has_h() const;
  inline void clear_h();
  static const int kHFieldNumber = 4000;
  inline ::google::protobuf::int32 h() const;
  inline void set_h(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:jc_res.Rectangle)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_w();
  inline void clear_has_w();
  inline void set_has_h();
  inline void clear_has_h();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  ::google::protobuf::int32 w_;
  ::google::protobuf::int32 h_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_Primitive_2eproto();
  friend void protobuf_AssignDesc_Primitive_2eproto();
  friend void protobuf_ShutdownFile_Primitive_2eproto();

  void InitAsDefaultInstance();
  static Rectangle* default_instance_;
};
// -------------------------------------------------------------------

class Size : public ::google::protobuf::Message {
 public:
  Size();
  virtual ~Size();

  Size(const Size& from);

  inline Size& operator=(const Size& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Size& default_instance();

  void Swap(Size* other);

  // implements Message ----------------------------------------------

  Size* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Size& from);
  void MergeFrom(const Size& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 w = 1000;
  inline bool has_w() const;
  inline void clear_w();
  static const int kWFieldNumber = 1000;
  inline ::google::protobuf::int32 w() const;
  inline void set_w(::google::protobuf::int32 value);

  // required int32 h = 2000;
  inline bool has_h() const;
  inline void clear_h();
  static const int kHFieldNumber = 2000;
  inline ::google::protobuf::int32 h() const;
  inline void set_h(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:jc_res.Size)
 private:
  inline void set_has_w();
  inline void clear_has_w();
  inline void set_has_h();
  inline void clear_has_h();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 w_;
  ::google::protobuf::int32 h_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_Primitive_2eproto();
  friend void protobuf_AssignDesc_Primitive_2eproto();
  friend void protobuf_ShutdownFile_Primitive_2eproto();

  void InitAsDefaultInstance();
  static Size* default_instance_;
};
// ===================================================================


// ===================================================================

// Rectangle

// required int32 x = 1000;
inline bool Rectangle::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Rectangle::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Rectangle::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Rectangle::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 Rectangle::x() const {
  return x_;
}
inline void Rectangle::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
}

// required int32 y = 2000;
inline bool Rectangle::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Rectangle::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Rectangle::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Rectangle::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 Rectangle::y() const {
  return y_;
}
inline void Rectangle::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
}

// required int32 w = 3000;
inline bool Rectangle::has_w() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Rectangle::set_has_w() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Rectangle::clear_has_w() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Rectangle::clear_w() {
  w_ = 0;
  clear_has_w();
}
inline ::google::protobuf::int32 Rectangle::w() const {
  return w_;
}
inline void Rectangle::set_w(::google::protobuf::int32 value) {
  set_has_w();
  w_ = value;
}

// required int32 h = 4000;
inline bool Rectangle::has_h() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Rectangle::set_has_h() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Rectangle::clear_has_h() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Rectangle::clear_h() {
  h_ = 0;
  clear_has_h();
}
inline ::google::protobuf::int32 Rectangle::h() const {
  return h_;
}
inline void Rectangle::set_h(::google::protobuf::int32 value) {
  set_has_h();
  h_ = value;
}

// -------------------------------------------------------------------

// Size

// required int32 w = 1000;
inline bool Size::has_w() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Size::set_has_w() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Size::clear_has_w() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Size::clear_w() {
  w_ = 0;
  clear_has_w();
}
inline ::google::protobuf::int32 Size::w() const {
  return w_;
}
inline void Size::set_w(::google::protobuf::int32 value) {
  set_has_w();
  w_ = value;
}

// required int32 h = 2000;
inline bool Size::has_h() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Size::set_has_h() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Size::clear_has_h() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Size::clear_h() {
  h_ = 0;
  clear_has_h();
}
inline ::google::protobuf::int32 Size::h() const {
  return h_;
}
inline void Size::set_h(::google::protobuf::int32 value) {
  set_has_h();
  h_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace jc_res

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Primitive_2eproto__INCLUDED
