#! /bin/sh

if [ ! -e AndroidManifest.xml ]; then
    echo "is not Android Project directory..."
    exit 1
fi

ANDROID_VERSION=android-15
OUTPUT_PATH=../../sources/

#
echo "android classes --------------"
java -jar "${JOINTCODING_HOME}/bin/jcj2c.jar" --source "./bin/classes/com/eaglesakura/jc/" --output "${OUTPUT_PATH}/gen/android-classes" --library "${ANDROID_HOME}/platforms/${ANDROID_VERSION}/android.jar" "./bin/classes"  | grep "export"

java -jar "${JOINTCODING_HOME}/bin/jcj2c.jar" --source "./bin/classes/com/google/" --output "${OUTPUT_PATH}/gen/android-gclasses" --library "${ANDROID_HOME}/platforms/${ANDROID_VERSION}/android.jar" "./bin/classes"  | grep "export"

#
echo "protocols --------------"
java -jar "${JOINTCODING_HOME}/bin/jcj2c.jar" --source "./bin/classes/com/eaglesakura/jcprotocol/" --output "${OUTPUT_PATH}/gen/protocol" --library "${ANDROID_HOME}/platforms/${ANDROID_VERSION}/android.jar" | grep "export"


